-- Tabla de palets
CREATE TABLE palets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    usuario_creador_id UUID NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Tabla de paquetes
CREATE TABLE paquetes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    palet_id BIGINT REFERENCES palets(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    codigo VARCHAR(255),
    cantidad INTEGER NOT NULL,
    vencimiento DATE,
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Tabla de auditoría
CREATE TABLE auditoria (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id UUID NOT NULL,
    accion VARCHAR(50) NOT NULL,
    entidad VARCHAR(50) NOT NULL,
    entidad_id BIGINT,
    detalle JSONB,
    fecha TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Índices
CREATE INDEX idx_palets_usuario ON palets(usuario_creador_id);
CREATE INDEX idx_paquetes_palet ON paquetes(palet_id);
CREATE INDEX idx_auditoria_usuario ON auditoria(usuario_id);

-- ===== DESHABILITAR RLS Y LIMPIAR POLÍTICAS ANTIGUAS =====
ALTER TABLE palets DISABLE ROW LEVEL SECURITY;
ALTER TABLE paquetes DISABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria DISABLE ROW LEVEL SECURITY;

-- Eliminar cualquier política existente
DROP POLICY IF EXISTS "palets_select" ON palets;
DROP POLICY IF EXISTS "palets_insert" ON palets;
DROP POLICY IF EXISTS "palets_update" ON palets;
DROP POLICY IF EXISTS "palets_delete" ON palets;

DROP POLICY IF EXISTS "paquetes_select" ON paquetes;
DROP POLICY IF EXISTS "paquetes_insert" ON paquetes;
DROP POLICY IF EXISTS "paquetes_update" ON paquetes;
DROP POLICY IF EXISTS "paquetes_delete" ON paquetes;

DROP POLICY IF EXISTS "auditoria_select" ON auditoria;
DROP POLICY IF EXISTS "auditoria_insert" ON auditoria;

-- ===== HABILITAR RLS =====
ALTER TABLE palets ENABLE ROW LEVEL SECURITY;
ALTER TABLE paquetes ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria ENABLE ROW LEVEL SECURITY;

-- ===== CREAR NUEVAS POLÍTICAS PERMISIVAS (MODO DEMO) =====
-- Para palets: Permitir todas las operaciones
CREATE POLICY "palets_todas_operaciones" ON palets FOR SELECT USING (true);
CREATE POLICY "palets_insertar" ON palets FOR INSERT WITH CHECK (true);
CREATE POLICY "palets_actualizar" ON palets FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "palets_eliminar" ON palets FOR DELETE USING (true);

-- Para paquetes: Permitir todas las operaciones
CREATE POLICY "paquetes_todas_operaciones" ON paquetes FOR SELECT USING (true);
CREATE POLICY "paquetes_insertar" ON paquetes FOR INSERT WITH CHECK (true);
CREATE POLICY "paquetes_actualizar" ON paquetes FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "paquetes_eliminar" ON paquetes FOR DELETE USING (true);

-- Para auditoría: Solo lectura sin restricciones
CREATE POLICY "auditoria_todas_operaciones" ON auditoria FOR SELECT USING (true);
CREATE POLICY "auditoria_insertar" ON auditoria FOR INSERT WITH CHECK (true);